"""Shared constants（共享常量） for multimodal MiniMax tools."""

DEFAULT_VOICE_ID = "female-shaonv-jingpin"
DEFAULT_SPEECH_MODEL = "speech-2.8-hd"
DEFAULT_MUSIC_MODEL = "music-2.5"
DEFAULT_SPEED = 1.0
DEFAULT_VOLUME = 1.0
DEFAULT_PITCH = 0
DEFAULT_EMOTION = "happy"
DEFAULT_SAMPLE_RATE = 32000
DEFAULT_BITRATE = 128000
DEFAULT_CHANNEL = 1
DEFAULT_FORMAT = "mp3"
DEFAULT_LANGUAGE_BOOST = "auto"

DEFAULT_T2V_MODEL = "MiniMax-Hailuo-2.3"
DEFAULT_T2I_MODEL = "image-01"

RESOURCE_MODE_LOCAL = "local"
RESOURCE_MODE_URL = "url"

DEFAULT_HTTP_TIMEOUT_SECONDS = 30
DEFAULT_MUSIC_TIMEOUT_SECONDS = 120
DEFAULT_MAX_HTTP_DOWNLOAD_BYTES = 100 * 1024 * 1024
